/**
 * ListenService Version und Build Konstanten
 *
 * API-Version: 1.0
 * Datum:       11.10.2018
 *
 * @module speech/listen
 * @author SB
 */


// global

import {
    SPEECHSERVICE_VERSION_NUMBER,
    SPEECHSERVICE_VERSION_BUILD,
    SPEECHSERVICE_VERSION_TYPE,
    SPEECHSERVICE_VERSION_DATE
} from './../const/speech-service-version';


// Versions-Konstanten

export const LISTENSERVICE_VERSION_NUMBER = SPEECHSERVICE_VERSION_NUMBER;
export const LISTENSERVICE_VERSION_BUILD = SPEECHSERVICE_VERSION_BUILD;
export const LISTENSERVICE_VERSION_TYPE = SPEECHSERVICE_VERSION_TYPE;
export const LISTENSERVICE_VERSION_DATE = SPEECHSERVICE_VERSION_DATE;

// tslint:disable-next-line
export const LISTENSERVICE_VERSION_STRING = LISTENSERVICE_VERSION_NUMBER + '.' + LISTENSERVICE_VERSION_BUILD + ' vom ' + LISTENSERVICE_VERSION_DATE + ' (' + LISTENSERVICE_VERSION_TYPE + ')';
export const LISTENSERVICE_API_VERSION = LISTENSERVICE_VERSION_STRING;
