/**
 * ActionService Version und Build Konstanten
 *
 * API-Version: 1.0
 * Datum:       15.09.2018
 *
 * @module speech/action
 * @author SB
 */


// global

import {
    SPEECHSERVICE_VERSION_NUMBER,
    SPEECHSERVICE_VERSION_BUILD,
    SPEECHSERVICE_VERSION_TYPE,
    SPEECHSERVICE_VERSION_DATE
} from './../const/speech-service-version';


// Versions-Konstanten

export const ACTIONSERVICE_VERSION_NUMBER = SPEECHSERVICE_VERSION_NUMBER;
export const ACTIONSERVICE_VERSION_BUILD = SPEECHSERVICE_VERSION_BUILD;
export const ACTIONSERVICE_VERSION_TYPE = SPEECHSERVICE_VERSION_TYPE;
export const ACTIONSERVICE_VERSION_DATE = SPEECHSERVICE_VERSION_DATE;

// tslint:disable-next-line
export const ACTIONSERVICE_VERSION_STRING = ACTIONSERVICE_VERSION_NUMBER + '.' + ACTIONSERVICE_VERSION_BUILD + ' vom ' + ACTIONSERVICE_VERSION_DATE + ' (' + ACTIONSERVICE_VERSION_TYPE + ')';
export const ACTIONSERVICE_API_VERSION = ACTIONSERVICE_VERSION_STRING;
