/**
 * IntentService Version und Build Konstanten
 *
 * API-Version: 1.0
 * Datum:       28.11.2018
 *
 * @module speech/intent
 * @author SB
 */


// global

import {
    SPEECHSERVICE_VERSION_NUMBER,
    SPEECHSERVICE_VERSION_BUILD,
    SPEECHSERVICE_VERSION_TYPE,
    SPEECHSERVICE_VERSION_DATE
} from './../const/speech-service-version';


// Versions-Konstanten

export const INTENTSERVICE_VERSION_NUMBER = SPEECHSERVICE_VERSION_NUMBER;
export const INTENTSERVICE_VERSION_BUILD = SPEECHSERVICE_VERSION_BUILD;
export const INTENTSERVICE_VERSION_TYPE = SPEECHSERVICE_VERSION_TYPE;
export const INTENTSERVICE_VERSION_DATE = SPEECHSERVICE_VERSION_DATE;

// tslint:disable-next-line
export const INTENTSERVICE_VERSION_STRING = INTENTSERVICE_VERSION_NUMBER + '.' + INTENTSERVICE_VERSION_BUILD + ' vom ' + INTENTSERVICE_VERSION_DATE + ' (' + INTENTSERVICE_VERSION_TYPE + ')';
export const INTENTSERVICE_API_VERSION = INTENTSERVICE_VERSION_STRING;
